In [2]:
import pandas as pd
import numpy as np

## Ejercicio 1

 ¿Qué diferencia hay entre una Serie y un DataFrame?

Ambas son estructuras de datos de Pandas, pero las series son estructuras en una dimensión y los DataFrame son estructuras en dos dimensiones (tablas).

## Ejercicio 2 : Series

Momento de trabajar con Series. Contestad a las siguientes preguntas:

Crea dos listas:
- Una que se llame "valores" que tenga 7 números aleatorios.
- Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [3]:
#Hemos consultado: https://stackoverflow.com/a/25174767 para obtener una muestra con números no duplicados
valores = np.random.choice(range(20), 7, replace=False)
valores

array([15, 19,  2, 11, 18,  8,  0])

In [4]:
indices = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]

- A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [5]:
serie1 = pd.Series(indices,valores)
serie1

15        lunes
19       martes
2     miercoles
11       jueves
18      viernes
8        sabado
0       domingo
dtype: object

- A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. 

In [6]:
def diccionizador(val,ind):
    diccionario = dict(zip(val, ind))
    return diccionario

        

In [7]:
diccionizador(valores,indices)

{15: 'lunes',
 19: 'martes',
 2: 'miercoles',
 11: 'jueves',
 18: 'viernes',
 8: 'sabado',
 0: 'domingo'}

In [8]:
diccionario = diccionizador(indices,valores)
diccionario

{'lunes': 15,
 'martes': 19,
 'miercoles': 2,
 'jueves': 11,
 'viernes': 18,
 'sabado': 8,
 'domingo': 0}

- Crea una Serie con el diccionario creado en el punto anterior

In [9]:
series2 = pd.Series(diccionario)
series2

lunes        15
martes       19
miercoles     2
jueves       11
viernes      18
sabado        8
domingo       0
dtype: int64

- ¿Qué forma tiene esta última Serie?

In [10]:
series2.shape
print(f"Nuestra serie tiene una forma de {series2.shape} filas")

Nuestra serie tiene una forma de (7,) filas


- ¿Qué tipo de datos tiene?

In [11]:
series2.dtypes

dtype('int64')

- ¿Qué tamaño tiene?

In [12]:
series2.size

7

- ¿Cuáles son los índices de la Serie?

In [13]:
series2.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

- ¿Y los values?

In [14]:
series2.values

array([15, 19,  2, 11, 18,  8,  0])

- Extraed el valor para el índice "lunes"

In [15]:
series2["lunes"]

15

- Extraed el valor para el índice "lunes", "martes" y "miércoles".

In [16]:
series2["lunes":"miercoles"]

lunes        15
martes       19
miercoles     2
dtype: int64

- Extraed el valor para el índice "lunes" y "domingo".

In [17]:
series2[[0,-1]]

lunes      15
domingo     0
dtype: int64

## Ejercicio 3 : DataFrames
- Cread un array de dos dimensiones con 4 filas y 3 columnas.

In [18]:
array_ej3 = np.random.randint(0,50,(4,3))
array_ej3

array([[41, 35, 11],
       [16, 34, 15],
       [27, 24, 25],
       [43,  6, 25]])

- Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [19]:
df_ejer3 = pd.DataFrame(array_ej3, columns = ['España', 'Francia', 'Italia'])
df_ejer3

España  Francia  Italia
0      41       35      11
1      16       34      15
2      27       24      25
3      43        6      25

- Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:

In [22]:
df_medallas = pd.read_csv("medallas.csv", index_col=["País"])
df_medallas

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

 NOTA: Para evitar problemas guardad el archivo medallas.csv a la misma altura (en la misma carpeta) que el jupyter donde estamos trabajando.

- Usando el loc extraed todas las columnas de la fila de Tailandia.

In [23]:
df_medallas.loc["Tailandia",]

Unnamed: 0      7
Oro           132
Plata         175
Bronce        278
Name: Tailandia, dtype: int64

- Usando el loc extraed todas las columnas de China e Irán.

In [68]:
China = df_medallas.loc["China",]
Irán = df_medallas.loc["Irán",]
print(China,Irán)

Unnamed: 0       1
Oro           1473
Plata          994
Bronce         720
Name: China, dtype: int64 Unnamed: 0      4
Oro           179
Plata         181
Bronce        197
Name: Irán, dtype: int64


- Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [110]:
colum_China_Iran =df_medallas.loc["China",["Oro","Plata","Bronce"]], df_medallas.loc["Irán",["Oro","Plata","Bronce"]]
colum_China_Iran

(Oro       1473
 Plata      994
 Bronce     720
 Name: China, dtype: int64,
 Oro       179
 Plata     181
 Bronce    197
 Name: Irán, dtype: int64)

- Usando el iloc extraed la información de la India. Devolved todas las columnas.

In [78]:
df_medallas.iloc[5,:]

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

- Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [83]:
df_medallas.iloc[1::2,:]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

- Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

In [92]:
df_medallas.iloc[1::2,1:]

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

Contestad a las siguientes preguntas:

- ¿Qué país consiguió más de 200 medallas de oro?

In [93]:
df_medallas.loc[df_medallas.Oro > 200, :]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

In [94]:
df_medallas.iloc[list((df_medallas.Oro > 200) & (df_medallas.Plata > 1000)), :]

Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985

- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [97]:
df_medallas.iloc[list((df_medallas.Oro > 200) | (df_medallas.Bronce > 700)), :]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

- Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.

In [ ]:
df_medallas.drop(['Unnamed:0'], axis=1)

In [ ]:
df_medallas.drop(df_medallas["Unnamed:0"])

- Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [128]:
df_medallas.assign(total=df_medallas["Oro"] + df_medallas["Plata"] + df_medallas["Bronce"])

Unnamed: 0   Oro  Plata  Bronce  total
País                                                   
China                     1  1473    994     720   3187
Japón                     2  1032   1037     985   3054
Corea del Sur             3   745    663     827   2235
Irán                      4   179    181     197    557
Kazajistán                5   155    158     224    537
India                     6   154    202     315    671
Tailandia                 7   132    175     278    585
Indonesia                 8   112    131     240    483
China Taipéi              9    99    144     276    519
Corea del Norte          10    91    120     235    446