1. Cargad los tres ficheros nombrados anteriormente y los exploramos para familizarizarnos con ellos y saber que información tienen en común y debatir con tu compañera como podríamos juntar toda la información.

In [91]:
import pandas as pd
import numpy as np

In [92]:
attacks = pd.read_csv('../Pandas/attacks_1_3.csv')
attadicional = pd.read_csv('../Pandas/attacks_adicional.csv')
atthist = pd.read_csv('../Pandas/attacks_historico.csv')

In [93]:
attacks.head(3)

Unnamed: 0   case_number    year        type country        area  \
0           0    2018.06.25  2018.0     Boating     USA  California   
1           6  2018.06.03.a  2018.0  Unprovoked  BRAZIL  Pernambuco   
2           8  2018.05.26.b  2018.0  Unprovoked     USA     Florida   

                       location  activity                    name sex age  \
0   Oceanside, San Diego County  Paddling             Julie Wolfe   F  57   
1         Piedade Beach, Recife  Swimming  Jose Ernesto da Silva    M  18   
2  Cocoa Beach, Brevard  County   Walking               Cody High   M  15   

             time         species                       pdf  \
0           18h00     White shark      2018.06.25-Wolfe.pdf   
1  Late afternoon     Tiger shark  2018.06.03.a-daSilva.pdf   
2           17h00  Bull shark, 6'     2018.05.26.b-High.pdf   

                                        href_formula  \
0  http://sharkattackfile.net/spreadsheets/pdf_di...   
1  http://sharkattackfile.net/spreadsheets/pdf_di...   
2  http://sharkattackfile.net/spreadsheets/pdf_di...   

                                                href      siglo  
0  http://sharkattackfile.net/spreadsheets/pdf_di...  siglo-XXI  
1  http://sharkattackfile.net/spreadsheets/pdf_di...  siglo-XXI  
2  http://sharkattackfile.net/spreadsheets/pdf_di...  siglo-XXI

In [94]:
attadicional.head(3)

Unnamed: 0 Case Number Fatal (Y/N)  \
0           0  2018.06.25           N   
1           1  2018.06.18           N   
2           2  2018.06.09           N   

                                              Injury         Date  
0  No injury to occupant, outrigger canoe and pad...  25-Jun-2018  
1                         Minor injury to left thigh  18-Jun-2018  
2       Injury to left lower leg from surfboard skeg  09-Jun-2018

In [95]:
atthist.head(3)

Unnamed: 0   Case Number    Year        Type     Country      Area  \
0        6132    1800.00.00  1800.0  Unprovoked  SEYCHELLES  St. Anne   
1        6133  1797.05.28.R  1797.0  Unprovoked         NaN       NaN   
2        6134    1792.09.12  1792.0    Provoked     ENGLAND       NaN   

              Location                         Activity   Name Sex   ...  \
0                  NaN  a corsair's boat was overturned    NaN    F  ...   
1                  NaN                Dropped overboard  child  NaN  ...   
2  On the Thames River                          Fishing   male    M  ...   

  Species            Investigator or Source                          pdf  \
0      NaN               V. C. Harvey-Brain  1800.00.00-Corsair-boat.pdf   
1      NaN           The Observer 5/28/1797  1797.05.28.R-Cloverdale.pdf   
2      NaN  The Waterford Herald, 9/15/1792        1792.09.12-Thames.pdf   

                                        href formula  \
0  http://sharkattackfile.net/spreadsheets/pdf_di...   
1  http://sharkattackfile.net/spreadsheets/pdf_di...   
2  http://sharkattackfile.net/spreadsheets/pdf_di...   

                                                href Case Number.1  \
0  http://sharkattackfile.net/spreadsheets/pdf_di...    1800.00.00   
1  http://sharkattackfile.net/spreadsheets/pdf_di...  1797.05.28.R   
2  http://sharkattackfile.net/spreadsheets/pdf_di...    1792.09.12   

  Case Number.2 original order Unnamed: 22  Unnamed: 23  
0    1800.00.00          171.0         NaN          NaN  
1  1797.05.28.R          170.0         NaN          NaN  
2    1792.09.12          169.0         NaN          NaN  

[3 rows x 22 columns]

In [96]:
attacks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1502 entries, 0 to 1501
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    1502 non-null   int64  
 1   case_number   1502 non-null   object 
 2   year          1502 non-null   float64
 3   type          1502 non-null   object 
 4   country       1502 non-null   object 
 5   area          1502 non-null   object 
 6   location      1502 non-null   object 
 7   activity      1502 non-null   object 
 8   name          1502 non-null   object 
 9   sex           1502 non-null   object 
 10  age           1502 non-null   object 
 11  time          1502 non-null   object 
 12  species       1502 non-null   object 
 13  pdf           1502 non-null   object 
 14  href_formula  1502 non-null   object 
 15  href          1502 non-null   object 
 16  siglo         1502 non-null   object 
dtypes: float64(1), int64(1), object(15)
memory usage: 199.6+ KB


In [97]:
attadicional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6288 entries, 0 to 6287
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   6288 non-null   int64 
 1   Case Number  6287 non-null   object
 2   Fatal (Y/N)  5751 non-null   object
 3   Injury       6258 non-null   object
 4   Date         6286 non-null   object
dtypes: int64(1), object(4)
memory usage: 245.8+ KB


In [98]:
atthist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Unnamed: 0              170 non-null    int64  
 1   Case Number             170 non-null    object 
 2   Year                    170 non-null    float64
 3   Type                    170 non-null    object 
 4   Country                 160 non-null    object 
 5   Area                    124 non-null    object 
 6   Location                119 non-null    object 
 7   Activity                139 non-null    object 
 8   Name                    161 non-null    object 
 9   Sex                     156 non-null    object 
 10  Age                     16 non-null     object 
 11  Time                    10 non-null     object 
 12  Species                 44 non-null     object 
 13  Investigator or Source  169 non-null    object 
 14  pdf                     170 non-null    ob

        Podemos observar que attacks_historico.csv (atthist) las columnas son las mismas que en nuestro archivo original de attacks.csv antes de la depuración.

2. Chequead que los nombres de las columnas ver si se llaman iguales entre dataframes . ¿Están todas en minúsculas? ¿Tienen espacios? En caso de que no sean todas iguales unificad el nombre de las columnas.

In [18]:
#vamos a crear copias para cada archivo:
attacks2 = attacks.copy()
atthist2 = atthist.copy()
attadic2 = attadicional.copy()

        Es necesario homogeneizar los formatos de los nombres de las columnas (están capitalizadas) y quitar los espacios para que se parezca lo máximo posible a nuestro csv attacks. También hay que quitar las columnas y los nulos que borramos en ejercicios anteriores.

        * limpieza de atthist:

In [99]:
#quitamos los espacios delante y detrás de los nombres:
atthist.columns = atthist.columns.str.strip()
#quitamos los espacios y los reemplazamos por '_':
atthist.columns = atthist.columns.str.replace(" ", "_").str.lower()
atthist.columns
#Nos pasa lo siguiente que no sabemos como resolver: Sobre los originales se guardan los cambios aplicados con el .strip() pero no con las copias

Index(['unnamed:_0', 'case_number', 'year', 'type', 'country', 'area',
       'location', 'activity', 'name', 'sex', 'age', 'time', 'species',
       'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number.1', 'case_number.2', 'original_order', 'unnamed:_22',
       'unnamed:_23'],
      dtype='object')

In [101]:
attacks2.columns

Index(['unnamed: 0', 'case_number', 'year', 'type', 'country', 'area',
       'location', 'activity', 'name', 'sex_', 'age', 'time', 'species_',
       'pdf', 'href_formula', 'href', 'siglo'],
      dtype='object')

In [100]:
atthist2 = atthist.copy()
atthist2.head(2)

unnamed:_0   case_number    year        type     country      area  \
0        6132    1800.00.00  1800.0  Unprovoked  SEYCHELLES  St. Anne   
1        6133  1797.05.28.R  1797.0  Unprovoked         NaN       NaN   

  location                         activity   name  sex  ... species  \
0      NaN  a corsair's boat was overturned    NaN    F  ...     NaN   
1      NaN                Dropped overboard  child  NaN  ...     NaN   

   investigator_or_source                          pdf  \
0      V. C. Harvey-Brain  1800.00.00-Corsair-boat.pdf   
1  The Observer 5/28/1797  1797.05.28.R-Cloverdale.pdf   

                                        href_formula  \
0  http://sharkattackfile.net/spreadsheets/pdf_di...   
1  http://sharkattackfile.net/spreadsheets/pdf_di...   

                                                href case_number.1  \
0  http://sharkattackfile.net/spreadsheets/pdf_di...    1800.00.00   
1  http://sharkattackfile.net/spreadsheets/pdf_di...  1797.05.28.R   

  case_number.2 original_order unnamed:_22  unnamed:_23  
0    1800.00.00          171.0         NaN          NaN  
1  1797.05.28.R          170.0         NaN          NaN  

[2 rows x 22 columns]

In [62]:
#borramos las columnas que no nos hacen falta. no borramos unnamed 0 ya que nos ha vuelto a aparecer en el archivo attacks_1_3.
atthist2.drop(['investigator_or_source', 'case_number.1', 'case_number.2', 'original_order', 'unnamed:_22',
       'unnamed:_23'], inplace=True, axis=1)
atthist2.columns

Index(['unnamed:_0', 'case_number', 'year', 'type', 'country', 'area',
       'location', 'activity', 'name', 'sex', 'age', 'time', 'species', 'pdf',
       'href_formula', 'href'],
      dtype='object')

In [71]:
#borramos también los casos nulos en atthist2:
atthist2_sin_nulos = atthist2.dropna()

print(f"Hemos borrado un total de {(atthist2.shape[0] - atthist2_sin_nulos.shape[0])} casos en la base de históricos")

Hemos borrado un total de 167 casos en la base de históricos


        Con relación a la longitud de las columnas, sabemos que la única columna que tiene ahora attacks2 que no tiene attthist2 es la columna de 'siglos'. Creamos la columna siglos en atthist2:

In [77]:
atthist2['year'].unique()

array([1800., 1797., 1792., 1791., 1788., 1787., 1786., 1785., 1784.,
       1783., 1780., 1779., 1776., 1771., 1767., 1764., 1758., 1753.,
       1751., 1749., 1755., 1748., 1742., 1738., 1733., 1723., 1721.,
       1703., 1700., 1642., 1638., 1637., 1617., 1595., 1580., 1555.,
       1554., 1543.,  500.,   77.,    5.,    0.])

In [83]:
#creamos la columna con los filtros:
        #[(db_sharks3['year'] < 1900), (db_sharks3['year'] < 2000), (db_sharks3['year'] >= 2000)]
siglos = [(atthist2['year'] == 1800), (atthist2['year'] < 1800), (atthist2['year'] < 1700), (atthist2['year'] < 1600)]
valores = ['siglo XIX', 'siglo-XVIII', 'siglo-XVII', 'siglo-XVI o anterior']

atthist2['siglo'] = np.select(siglos, valores)

In [86]:
#ahora, confirmamos que tienen la misma longitud
atthist2.columns == attacks2.columns
#

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True])

In [89]:
attacks2.columns = attacks2.columns.str.lower()
attacks2.columns

Index(['unnamed: 0', 'case_number', 'year', 'type', 'country', 'area',
       'location', 'activity', 'name', 'sex_', 'age', 'time', 'species_',
       'pdf', 'href_formula', 'href', 'siglo'],
      dtype='object')

In [90]:
atthist2.columns == attacks2.columns

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True])

In [88]:
attacks2.columns

Index(['Unnamed: 0', 'case_number', 'year', 'type', 'country', 'area',
       'location', 'activity', 'name', 'sex_', 'age', 'time', 'species_',
       'pdf', 'href_formula', 'href', 'siglo'],
      dtype='object')

In [41]:
attadic2.columns = attadic2.columns.str.strip().str.replace(" ", "_").str.lower()
attadic2.columns

Index(['unnamed:_0', 'case_number', 'fatal_(y/n)', 'injury', 'date'], dtype='object')

In [20]:
attadicional.columns = attadicional.columns.str.strip()


Index(['Unnamed:_0', 'Case_Number', 'Year', 'Type', 'Country', 'Area',
       'Location', 'Activity', 'Name', 'Sex_', 'Age', 'Time', 'Species_',
       'Investigator_or_Source', 'pdf', 'href_formula', 'href',
       'Case_Number.1', 'Case_Number.2', 'original_order', 'Unnamed:_22',
       'Unnamed:_23'],
      dtype='object')

In [12]:
atthist.drop(['Unnamed:_0', 'Investigator_or_Source', 'Case_Number.1', 'Case_Number.2', 'original_order', 'Unnamed:_22',
       'Unnamed:_23'], inplace=True)
atthist.columns

KeyError: "['Unnamed:_0', 'Investigator_or_Source', 'Case_Number.1', 'Case_Number.2', 'original_order', 'Unnamed:_22', 'Unnamed:_23'] not found in axis"

In [13]:
atthist.columns

Index(['Unnamed: 0', 'Case Number', 'Year', 'Type', 'Country', 'Area',
       'Location', 'Activity', 'Name', 'Sex ', 'Age', 'Time', 'Species ',
       'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')