In [2]:
import numpy as np

## Ejercicio 1
Cread tres arrays de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas en algunos casos.
El array de 2 dimensiones debe ser de 2 filas y 3 columnas
El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [3]:
lista1 = [15, 26, 8, 5, 9, 12]
lista2 = [19, 12, 9]
lista3 = [[[1,2,3],[1,2,3],[1,2,3]]]

In [4]:
array1 = np.array(lista1)
type(array1)

numpy.ndarray

In [5]:
array1

array([15, 26,  8,  5,  9, 12])

In [10]:
array1.ndim

1

In [7]:
array2 = np.array([lista2,lista3])
type(array2)

/tmp/ipykernel_6702/2793956789.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array2 = np.array([lista2,lista3])


numpy.ndarray

In [8]:
array2

array([list([19, 12, 9]), list([[[1, 2, 3], [1, 2, 3], [1, 2, 3]]])],
      dtype=object)

In [13]:
array2.ndim

1

In [9]:
array3 = np.random.randint(0,50,(2,3,5))
type(array3)

numpy.ndarray

In [10]:
array3

array([[[37, 48,  3, 35,  1],
        [ 6, 49, 40,  2, 43],
        [ 7, 49, 25,  0,  8]],

       [[37, 34, 17, 40, 47],
        [49, 24, 48,  5, 13],
        [ 1, 11, 43, 45,  0]]])

In [11]:
array3.ndim

3

## Ejercicio 2
Chequead las las propiedades básicas de cada array que os hayáis creado. Usad una función que nos devuelva las propiedades de una array que le pasemos.


In [12]:
def check_array(array):
    return type(array), array.ndim, array.shape, array.dtype
    


In [13]:
check_array(array1)
# la forma del array devuelve sólo el número de filas por ser unidimensional.

(numpy.ndarray, 1, (6,), dtype('int64'))

In [14]:
check_array(array2)

(numpy.ndarray, 1, (2,), dtype('O'))

In [15]:
check_array(array3)

(numpy.ndarray, 3, (2, 3, 5), dtype('int64'))

## Ejercicio 3
Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [16]:
array4 =np.identity(3)
type(array4)

numpy.ndarray

In [17]:
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Ejercicio 4
Cread una matriz de tres dimensiones de unos igual a la matriz de tres dimensiones creada en el primer ejercicio.


In [18]:
array_ej4 = np.ones_like(array4)
array_ej4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Ejercicio 5
Es el momento de hacer algunas operaciones entre arrays

- ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicio a la matriz identidad? ¿Por qué?

In [ ]:
np.add(array1,array4)

No se pueden sumar porque tienen dimensiones distintas.

- En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.


In [27]:
array1

array([15, 26,  8,  5,  9, 12])

In [21]:
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
array5 = np.random.randint(0,30,(3,3))
array5

array([[18, 21, 20],
       [23,  0,  1],
       [27,  4, 15]])

In [32]:
array_suma = np.add(array4,array5)
array_suma

array([[19., 21., 20.],
       [23.,  1.,  1.],
       [27.,  4., 16.]])

In [ ]:
#En un primer momento consideramos la opción de utilizar la función reshape
array4_b = np.reshape(array4,(6,))
array4_b


- Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [33]:
array_mult = np.multiply(array4,array5)
array_mult

array([[18.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0., 15.]])

- Dividid las dos matrices.

In [36]:
array_div = np.divide(array4,array5)
array_div

/tmp/ipykernel_6702/513807542.py:1: RuntimeWarning: divide by zero encountered in true_divide
  array_div = np.divide(array4,array5)


array([[0.05555556, 0.        , 0.        ],
       [0.        ,        inf, 0.        ],
       [0.        , 0.        , 0.06666667]])