In [2]:
import numpy as np

### Ejercicio 1
¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [13]:
np.random.seed(2)
arr1 = np.random.random_sample(9).round(2)
arr1


array([0.44, 0.03, 0.55, 0.44, 0.42, 0.33, 0.2 , 0.62, 0.3 ])

In [16]:
np.random.seed(2)
arr2 = np.random.random_sample(9).round(2)
arr2


array([0.44, 0.03, 0.55, 0.44, 0.42, 0.33, 0.2 , 0.62, 0.3 ])

### Ejercicio 2
### Cread los siguientes arrays:

* Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [21]:
arr3 = np.random.uniform(0, 10, size = (2,3,5)).astype(int)
arr3

array([[[4, 5, 3, 2, 3],
        [8, 7, 3, 0, 7],
        [2, 5, 0, 6, 3]],

       [[4, 4, 3, 5, 9],
        [1, 3, 0, 7, 6],
        [2, 4, 6, 6, 1]]])

In [23]:
arr3_unicos = np.unique(arr3)
arr3_unicos

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [24]:
arr4 = np.random.binomial(10,0.3, size= (2,3,5))
arr4

array([[[5, 4, 1, 5, 4],
        [4, 3, 2, 5, 3],
        [2, 2, 5, 3, 3]],

       [[3, 4, 3, 2, 3],
        [3, 3, 4, 2, 2],
        [1, 2, 0, 3, 2]]])

In [25]:
arr4_unicos = np.unique(arr4)
arr4_unicos

array([0, 1, 2, 3, 4, 5])

### Ejercicio 3
En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones y explicad cada uno de los outputs que os salgan.  

¿Qué significa cada una de estas operaciones que hemos ido extrayendo?:

* Elementos comunes entre los dos arrays

In [28]:
np.intersect1d(arr3,arr4)

array([0, 1, 2, 3, 4, 5])

In [27]:
np.intersect1d(arr4,arr3)

array([0, 1, 2, 3, 4, 5])

 Este método realiza un diagrama de Benn entre ambos arrays y nos devuelve los elementos comunes que hay entre ambos. En este caso, el orden de los arrays no altera el resultado.

* Unión de los dos arrays

In [29]:
np.union1d(arr3,arr4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.union1d(arr4,arr3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Este método devuelve todos los valores (sean comunes o no) contenidos en ambos arrays. Como en el caso anterior, el orden de los arrays no altera el resultado.

* ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [31]:
np.setdiff1d(arr3,arr4_unicos)

array([6, 7, 8, 9])

In [32]:
np.setdiff1d(arr4_unicos,arr3)

array([], dtype=int64)

Con este método obtenemos los valores que sí están en el array 3 (distribución uniforme) pero no en el array 4 (distribución binomial).

En este caso el orden de los arrays en el código sí es importante  a la hora de obtener los resultados deseados, ya que en la segunda línea de código lo que indica es que todos los valores contenidos en el array4 están en el array3.

### Ejercicio 4
Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [4]:
array1 = np.random.randint(1,100,size= 80)
array1

array([80, 16, 35, 66, 62, 30, 90, 63, 88, 85, 89, 94,  2, 56, 49,  3,  3,
       68, 63, 67, 25, 34, 87, 87, 28, 91, 48, 77,  5, 33, 11, 66, 25, 95,
        5, 31, 69, 37, 70, 92, 98, 40,  8, 66, 14, 59, 55, 39, 36, 30, 62,
        3, 55, 19, 27, 67, 81, 92, 34, 35, 68, 39, 10, 14, 58, 93, 73, 64,
       48, 54, 54, 65, 19, 63, 82, 50, 30, 88, 62, 98])

In [5]:
array2 = np.random.randint(1,100,size= 80)
array2

array([58, 48, 44, 74, 87, 79, 65, 60, 41, 82, 75,  5, 30, 94, 41, 67, 69,
       71, 58, 25, 48, 18, 36, 18, 65, 57,  8,  1, 92, 56, 66, 52, 61, 40,
       42, 34, 56,  7, 72, 11, 13, 13, 65, 44, 71, 92, 39, 65, 74, 82,  1,
       42, 11, 21, 12, 73, 95, 23, 26, 64, 66, 49, 72, 99, 86, 94, 51, 39,
       89,  6, 19, 69, 68, 41, 97, 32, 18, 70, 60,  9])

* Extraed los valores únicos de cada uno de los arrays y guardadlos en variables en las que se les llame array1 y array2.

In [8]:
array1 = np.unique(array1)
array1

array([ 2,  3,  5,  8, 10, 11, 14, 16, 19, 25, 27, 28, 30, 31, 33, 34, 35,
       36, 37, 39, 40, 48, 49, 50, 54, 55, 56, 58, 59, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 73, 77, 80, 81, 82, 85, 87, 88, 89, 90, 91, 92, 93,
       94, 95, 98])

In [9]:
array2 = np.unique(array2)
array2

array([ 1,  5,  6,  7,  8,  9, 11, 12, 13, 18, 19, 21, 23, 25, 26, 30, 32,
       34, 36, 39, 40, 41, 42, 44, 48, 49, 51, 52, 56, 57, 58, 60, 61, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 79, 82, 86, 87, 89, 92,
       94, 95, 97, 99])

* Identificad los elementos presentes en el array1 pero no en el array2 y asignarlo a una variable que se llame array3.

In [10]:
array3 = np.setdiff1d(array1,array2)
array3

array([ 2,  3, 10, 14, 16, 27, 28, 31, 33, 35, 37, 50, 54, 55, 59, 62, 63,
       77, 80, 81, 85, 88, 90, 91, 93, 98])

* Identificad los elementos presentes en el array2 pero no en el array1 y asignarlo a una variable que se llame array4.

In [11]:
array4 = np.setdiff1d(array2,array1)
array4

array([ 1,  6,  7,  9, 12, 13, 18, 21, 23, 26, 32, 41, 42, 44, 51, 52, 57,
       60, 61, 71, 72, 74, 75, 79, 86, 97, 99])

* Identificad los elementos presentes en ambos arrays y asignarlos a una variable que se llame array5.

In [12]:
array5 = np.intersect1d(array1,array2)
array5

array([ 5,  8, 11, 19, 25, 30, 34, 36, 39, 40, 48, 49, 56, 58, 64, 65, 66,
       67, 68, 69, 70, 73, 82, 87, 89, 92, 94, 95])

* ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [ ]:
np.ndarray.size(array1,array2)

In [13]:
array1.size

54

In [14]:
array2.size

55

In [15]:
array3.size

26

In [16]:
array4.size

27

In [17]:
array5.size

28

El array 2 tiene un elemento más que el array 1. Asimismo, los arrays 3, 4 y 5 tienen cada uno un elemento más que el anterior.  