## Ejercicio 1
Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:

In [1]:
import numpy as np
import pandas as pd

In [7]:
ejercicio1 = np.random.rand(5, 3)
ejercicio1

array([[0.548487  , 0.19482402, 0.96244203],
       [0.24092082, 0.13018326, 0.03233572],
       [0.42593989, 0.15440494, 0.74896832],
       [0.17457391, 0.23222756, 0.33894262],
       [0.48413086, 0.58800743, 0.05571291]])

- El valor de la primera fila y la segunda columna.

In [12]:
ejercicio1[1, 2] #buscamos el valor según el conteo de Python

0.032335723216638024

- Los valores de la segunda fila y las dos primeras columnas.

In [14]:
ejercicio1[2, :2]

array([0.42593989, 0.15440494])

- Extraed las filas pares (incluyendo la 0) y todas las columnas

In [15]:
ejercicio1[::2]

array([[0.548487  , 0.19482402, 0.96244203],
       [0.42593989, 0.15440494, 0.74896832],
       [0.48413086, 0.58800743, 0.05571291]])

- Extraed los valores que sean mayores que 0.5

In [17]:
ejercicio1[ejercicio1 > 0.5]

array([0.548487  , 0.96244203, 0.74896832, 0.58800743])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [18]:
ejercicio1[(ejercicio1 < 0.2) | (ejercicio1 > 0.5)]

array([0.548487  , 0.19482402, 0.96244203, 0.13018326, 0.03233572,
       0.15440494, 0.74896832, 0.17457391, 0.58800743, 0.05571291])

- Cread dos array de tres dimensiones:
    - El primero de 2 matrices, 5 filas y 3 columnas.
    - El segundo de 3 matrices, 2 filas y 5 columnas

In [20]:
arrtri1 = np.random.randint(0, 50, (2, 5, 3))
arrtri1

array([[[24, 45, 44],
        [28, 31,  5],
        [ 5, 27, 24],
        [36, 17,  0],
        [19, 20, 29]],

       [[47,  1,  5],
        [ 1, 24, 20],
        [28, 23, 28],
        [26, 37, 10],
        [ 3, 27, 47]]])

In [21]:
arrtri2 = np.random.randint(0, 50, (3, 2, 5))
arrtri2

array([[[40, 41, 41, 39, 38],
        [36, 42, 27, 15, 39]],

       [[12, 41, 37,  1, 16],
        [11, 36, 22, 13, 12]],

       [[17, 43, 25, 38, 20],
        [ 9,  2, 16, 25, 43]]])

- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [22]:
def check_array(array):
    return type(array), array.ndim, array.shape, array.dtype

In [23]:
check_array(ejercicio1)

(numpy.ndarray, 2, (5, 3), dtype('float64'))

In [24]:
check_array(arrtri1)

(numpy.ndarray, 3, (2, 5, 3), dtype('int32'))

In [25]:
check_array(arrtri2)

(numpy.ndarray, 3, (3, 2, 5), dtype('int32'))

- Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [26]:
arrtri1 + arrtri2

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

No podemos sumar los dos arrays ya que no pueden sumarse arrays tridimensionales de distintas dimensiones. Si sumamos dos arrays, siendo uno bidimensional (ejercicio1) y otro multidimensional no hay problema (se suman las columnas y filas de la bi en todas las filas y columnas de la multidimensional):

In [27]:
ejercicio1 + arrtri1

array([[[24.548487  , 45.19482402, 44.96244203],
        [28.24092082, 31.13018326,  5.03233572],
        [ 5.42593989, 27.15440494, 24.74896832],
        [36.17457391, 17.23222756,  0.33894262],
        [19.48413086, 20.58800743, 29.05571291]],

       [[47.548487  ,  1.19482402,  5.96244203],
        [ 1.24092082, 24.13018326, 20.03233572],
        [28.42593989, 23.15440494, 28.74896832],
        [26.17457391, 37.23222756, 10.33894262],
        [ 3.48413086, 27.58800743, 47.05571291]]])

- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
    - .reshape()
    - .transpose()
- Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [42]:
arrtri1_b = np.reshape(arrtri1, (3, 5, 2))
arrtri1_b

array([[[24, 45],
        [44, 28],
        [31,  5],
        [ 5, 27],
        [24, 36]],

       [[17,  0],
        [19, 20],
        [29, 47],
        [ 1,  5],
        [ 1, 24]],

       [[20, 28],
        [23, 28],
        [26, 37],
        [10,  3],
        [27, 47]]])

In [52]:
arrtri2_b = np.transpose(arrtri2, (0, 2, 1))
arrtri2_b
#a efectos prácticos, lo estamos transformando / 'reshapeando' a arrtri2_b(3, 5, 2)

array([[[40, 36],
        [41, 42],
        [41, 27],
        [39, 15],
        [38, 39]],

       [[12, 11],
        [41, 36],
        [37, 22],
        [ 1, 13],
        [16, 12]],

       [[17,  9],
        [43,  2],
        [25, 16],
        [38, 25],
        [20, 43]]])

        - suma:

In [53]:
np.add(arrtri1_b, arrtri2_b)

array([[[64, 81],
        [85, 70],
        [72, 32],
        [44, 42],
        [62, 75]],

       [[29, 11],
        [60, 56],
        [66, 69],
        [ 2, 18],
        [17, 36]],

       [[37, 37],
        [66, 30],
        [51, 53],
        [48, 28],
        [47, 90]]])

        multiplicación:

In [54]:
np.multiply(arrtri1_b, arrtri2_b)

array([[[ 960, 1620],
        [1804, 1176],
        [1271,  135],
        [ 195,  405],
        [ 912, 1404]],

       [[ 204,    0],
        [ 779,  720],
        [1073, 1034],
        [   1,   65],
        [  16,  288]],

       [[ 340,  252],
        [ 989,   56],
        [ 650,  592],
        [ 380,   75],
        [ 540, 2021]]])

        división

In [55]:
np.divide(arrtri1_b, arrtri2_b)

array([[[ 0.6       ,  1.25      ],
        [ 1.07317073,  0.66666667],
        [ 0.75609756,  0.18518519],
        [ 0.12820513,  1.8       ],
        [ 0.63157895,  0.92307692]],

       [[ 1.41666667,  0.        ],
        [ 0.46341463,  0.55555556],
        [ 0.78378378,  2.13636364],
        [ 1.        ,  0.38461538],
        [ 0.0625    ,  2.        ]],

       [[ 1.17647059,  3.11111111],
        [ 0.53488372, 14.        ],
        [ 1.04      ,  2.3125    ],
        [ 0.26315789,  0.12      ],
        [ 1.35      ,  1.09302326]]])