### Ejercicio 1
Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [36]:
import numpy as np

In [37]:
arr1 = np.random.rand(2,3,5).round(1)
arr1

array([[[0.2, 0.5, 0.2, 0.5, 0.3],
        [0.2, 0.2, 0.9, 0.4, 0.6],
        [0.5, 0.9, 0.3, 0. , 0.8]],

       [[0.8, 0.6, 0.5, 0.8, 0.7],
        [0.1, 0.1, 0.4, 0.9, 0.8],
        [0.3, 0.6, 0.9, 0.1, 0.5]]])

### Ejercicio 2
Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [38]:
#optimización del proceso:
arr1_media = np.mean(arr1).round(1)
arr1_media

0.5

### Ejercicio 3
Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [39]:
arr1_max = np.max(arr1).round(1)
arr1_max

0.9

### Ejercicio 4
Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [40]:
#optimización del proceso:
arr1_min = np.min(arr1).round(1)
arr1_min

0.0

### Ejercicio 5
Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
* Si el valor del array es igual que la media, se reemplaza por "A".
* Si el valor del array es mayor que la media, se reemplaza por "B".
* Si el valor del array es menor que la media, se reemplaza por "C".
* Si el valor es igual que el máximo, se reemplaza por "D".
* Si el valor es igual que el mínimo, se reemplaza por "E".

¡¡ Pista !! Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.


In [41]:
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],
   [[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]]

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0
# nuestro array vacío debería quedar como este:
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],
   [["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]]

[[['A', 'B', 'C', 'B', 'C'],
  ['C', 'B', 'B', 'C', 'C'],
  ['D', 'C', 'C', 'B', 'C']],
 [['E', 'C', 'A', 'B', 'C'],
  ['B', 'B', 'B', 'E', 'B'],
  ['B', 'C', 'B', 'B', 'C']]]

In [42]:
arr_ejer5 = np.empty((2,3,5), dtype = str) 
arr_ejer5

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [46]:
forma = arr1.shape

for matrices in range(0, forma[0]):#hay que hacerlo con el ARR1- i ahora son las matrices. le pedimos la long. de las matrices
    for filas in range(0, forma[1]): #ahora son las filas dentro de cada matriz. le pedimos la long. de las columnas
        for n in range(0, forma[2]): #ahora iteramos por los numeros. le pedimos la long. de las filas
            
            if arr1[matrices, filas, n] == arr1_media:
                arr_ejer5[matrices, filas, n] = 'A'
            elif arr1[matrices, filas, n] > arr1_media:
                arr_ejer5[matrices, filas, n] = 'B'
            elif arr1[matrices, filas, n] < arr1_media:
                arr_ejer5[matrices, filas, n] = 'C'
            elif arr1[matrices, filas, n] == arr1_max:
                arr_ejer5[matrices, filas, n] = 'D'
            elif arr1[matrices, filas, n] == arr1_min:
                arr_ejer5[matrices, filas, n] = 'E'

print(arr_ejer5)

[[['C' 'A' 'C' 'A' 'C']
  ['C' 'C' 'B' 'C' 'B']
  ['A' 'B' 'C' 'C' 'B']]

 [['B' 'B' 'A' 'B' 'B']
  ['C' 'C' 'C' 'B' 'B']
  ['C' 'B' 'B' 'C' 'A']]]


### Ejercicio 6.
Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.

En este caso:
* Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1.
* Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2.
* Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [61]:
arr_ejer6 = np.empty(30)
arr_ejer6

array([1. , 0.8, 0.1, 0.9, 0. , 0.8, 0.7, 0.5, 0.2, 0.6, 0.9, 0.2, 0.8,
       0. , 0.1, 0.8, 0.4, 0.1, 0.9, 1. , 0.8, 0.1, 0.3, 0.6, 0.5, 0.7,
       0.6, 0.2, 0.6, 0.8])

In [50]:
arr_ejer5

array([[['C', 'A', 'C', 'A', 'C'],
        ['C', 'C', 'B', 'C', 'B'],
        ['A', 'B', 'C', 'C', 'B']],

       [['B', 'B', 'A', 'B', 'B'],
        ['C', 'C', 'C', 'B', 'B'],
        ['C', 'B', 'B', 'C', 'A']]], dtype='<U1')

In [65]:
for matrices in range(0, forma[0]): #hay que hacerlo con el ARR1- i ahora son las matrices. le pedimos la long. de las matrices
    c = 0 #creamos un contador para que itere
    for filas in range(0, forma[1]): #ahora son las filas dentro de cada matriz. le pedimos la long. de las columnas
        for n in range(0, forma[2]): #ahora iteramos por los numeros. le pedimos la long. de las filas
           
            if arr_ejer5[matrices, filas, n] == 'A' or arr_ejer5[matrices, filas, n] == 'B':
                arr_ejer6[c] = 1
            elif arr_ejer5[matrices, filas, n] == 'C' or arr_ejer5[matrices, filas, n] == 'D':
                arr_ejer6[c] = 2
            elif arr_ejer5[matrices, filas, n] == 'E':
                arr_ejer6[c] = 3
            c += 1
print(arr_ejer6)

[1. 1. 1. 1. 1. 2. 2. 2. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 2. 2. 1.
 1. 2. 1. 1. 2. 1.]


* Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [66]:
arr_ejer6.reshape(2, 3, 5)

array([[[1., 1., 1., 1., 1.],
        [2., 2., 2., 1., 1.],
        [2., 1., 1., 2., 1.]],

       [[1., 1., 1., 1., 1.],
        [2., 2., 2., 1., 1.],
        [2., 1., 1., 2., 1.]]])